// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.1
// source: proto/replicate_ops.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpectedPreviousIndex int64  `protobuf:"varint,1,opt,name=expectedPreviousIndex,proto3" json:"expectedPreviousIndex,omitempty"`
	Index                 int64  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Operation             string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Term                  int64  `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *CommitTransaction) Reset() {
	*x = CommitTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_replicate_ops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransaction) ProtoMessage() {}

func (x *CommitTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicate_ops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransaction.ProtoReflect.Descriptor instead.
func (*CommitTransaction) Descriptor() ([]byte, []int) {
	return file_proto_replicate_ops_proto_rawDescGZIP(), []int{0}
}

func (x *CommitTransaction) GetExpectedPreviousIndex() int64 {
	if x != nil {
		return x.ExpectedPreviousIndex
	}
	return 0
}

func (x *CommitTransaction) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitTransaction) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CommitTransaction) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type CommitOperationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogfileFinalIndex int64 `protobuf:"varint,1,opt,name=logfileFinalIndex,proto3" json:"logfileFinalIndex,omitempty"`
}

func (x *CommitOperationResponse) Reset() {
	*x = CommitOperationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_replicate_ops_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOperationResponse) ProtoMessage() {}

func (x *CommitOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicate_ops_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOperationResponse.ProtoReflect.Descriptor instead.
func (*CommitOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_replicate_ops_proto_rawDescGZIP(), []int{1}
}

func (x *CommitOperationResponse) GetLogfileFinalIndex() int64 {
	if x != nil {
		return x.LogfileFinalIndex
	}
	return 0
}

type ApplyOperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyOperationRequest) Reset() {
	*x = ApplyOperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_replicate_ops_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOperationRequest) ProtoMessage() {}

func (x *ApplyOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicate_ops_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOperationRequest.ProtoReflect.Descriptor instead.
func (*ApplyOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_replicate_ops_proto_rawDescGZIP(), []int{2}
}

type ApplyOperationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyOperationResponse) Reset() {
	*x = ApplyOperationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_replicate_ops_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOperationResponse) ProtoMessage() {}

func (x *ApplyOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicate_ops_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOperationResponse.ProtoReflect.Descriptor instead.
func (*ApplyOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_replicate_ops_proto_rawDescGZIP(), []int{3}
}

type ForwardOperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
}

func (x *ForwardOperationRequest) Reset() {
	*x = ForwardOperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_replicate_ops_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOperationRequest) ProtoMessage() {}

func (x *ForwardOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicate_ops_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOperationRequest.ProtoReflect.Descriptor instead.
func (*ForwardOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_replicate_ops_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type ForwardOperationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForwardOperationResponse) Reset() {
	*x = ForwardOperationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_replicate_ops_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOperationResponse) ProtoMessage() {}

func (x *ForwardOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replicate_ops_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOperationResponse.ProtoReflect.Descriptor instead.
func (*ForwardOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_replicate_ops_proto_rawDescGZIP(), []int{5}
}

var File_proto_replicate_ops_proto protoreflect.FileDescriptor

var file_proto_replicate_ops_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x5f, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x47, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6c, 0x6f,
	0x67, 0x66, 0x69, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x17, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x37, 0x0a, 0x17, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x92, 0x02, 0x0a, 0x19, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_replicate_ops_proto_rawDescOnce sync.Once
	file_proto_replicate_ops_proto_rawDescData = file_proto_replicate_ops_proto_rawDesc
)

func file_proto_replicate_ops_proto_rawDescGZIP() []byte {
	file_proto_replicate_ops_proto_rawDescOnce.Do(func() {
		file_proto_replicate_ops_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_replicate_ops_proto_rawDescData)
	})
	return file_proto_replicate_ops_proto_rawDescData
}

var file_proto_replicate_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_replicate_ops_proto_goTypes = []interface{}{
	(*CommitTransaction)(nil),        // 0: proto.CommitTransaction
	(*CommitOperationResponse)(nil),  // 1: proto.CommitOperationResponse
	(*ApplyOperationRequest)(nil),    // 2: proto.ApplyOperationRequest
	(*ApplyOperationResponse)(nil),   // 3: proto.ApplyOperationResponse
	(*ForwardOperationRequest)(nil),  // 4: proto.ForwardOperationRequest
	(*ForwardOperationResponse)(nil), // 5: proto.ForwardOperationResponse
}
var file_proto_replicate_ops_proto_depIdxs = []int32{
	0, // 0: proto.ReplicateOperationService.CommitOperation:input_type -> proto.CommitTransaction
	2, // 1: proto.ReplicateOperationService.ApplyOperation:input_type -> proto.ApplyOperationRequest
	4, // 2: proto.ReplicateOperationService.ForwardOperation:input_type -> proto.ForwardOperationRequest
	1, // 3: proto.ReplicateOperationService.CommitOperation:output_type -> proto.CommitOperationResponse
	3, // 4: proto.ReplicateOperationService.ApplyOperation:output_type -> proto.ApplyOperationResponse
	5, // 5: proto.ReplicateOperationService.ForwardOperation:output_type -> proto.ForwardOperationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_replicate_ops_proto_init() }
func file_proto_replicate_ops_proto_init() {
	if File_proto_replicate_ops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_replicate_ops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_replicate_ops_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitOperationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_replicate_ops_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyOperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_replicate_ops_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyOperationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_replicate_ops_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardOperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_replicate_ops_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardOperationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_replicate_ops_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_replicate_ops_proto_goTypes,
		DependencyIndexes: file_proto_replicate_ops_proto_depIdxs,
		MessageInfos:      file_proto_replicate_ops_proto_msgTypes,
	}.Build()
	File_proto_replicate_ops_proto = out.File
	file_proto_replicate_ops_proto_rawDesc = nil
	file_proto_replicate_ops_proto_goTypes = nil
	file_proto_replicate_ops_proto_depIdxs = nil
}
